on: push
name: Slack Notification Demo
jobs:
    slackNotification:
      name: Slack Notification Demo
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: Slack Notification Demo
        uses: bryan-nice/slack-notification@master
        env:
          SLACK_WEBHOOK: https://hooks.slack.com/services/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
          SLACK_TITLE: 'Slack Notification Githu'
          SLACK_MESSAGE: 'Demo''ing the Slack Notification'
          SLACK_CHANNEL:  https://oleksakravchuk.slack.com/archives/CQMS0225D
