on: [push,pull_request,issues,issue_comment,fork]
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.slaktest }}
        SLACK_ICON: https://www.smartdeploy.ai/images/logo.svg
        SLACK_USERNAME: SmartDeployAI 
